version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    reviewers:
      - "axone-protocol/maintainers"
    assignees:
      - "axone-protocol/maintainers"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "axone-protocol/maintainers"
    assignees:
      - "axone-protocol/maintainers"
