run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 20
    skip-tests: true
  funlen:
    statements: 65
  godot:
    scope: declarations # comments to be checked: `declarations` (default), `toplevel`, or `all`
  lll:
    line-length: 135
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: snake
output:
  uniq-by-line: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - source: "^//\\s*go:generate\\s"
      linters:
        - lll
    - source: "(noinspection|TODO)"
      linters:
        - godot
    - source: "//noinspection"
      linters:
        - gocritic
    - source: "^\\s+if _, ok := err\\.\\([^.]+\\.InternalError\\); ok {"
      linters:
        - errorlint
    - path: "_test\\.go"
      linters:
        - dupl
        - funlen
        - goconst
    - path: "_test\\.go"
      linters:
        - revive
      text: "dot-imports:"
